// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLmuc8UQYqT1YX07B8F4bkhRMbn5p-ek4',
    appId: '1:400663275175:web:ca52a37849f7b059351d82',
    messagingSenderId: '400663275175',
    projectId: 'dhikrs-2b082',
    authDomain: 'dhikrs-2b082.firebaseapp.com',
    storageBucket: 'dhikrs-2b082.firebasestorage.app',
    measurementId: 'G-XP88T3N7HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKdiiDwXxtm5GZVSLVZuBaFyZ3cC4Oii0',
    appId: '1:400663275175:android:a2154ca6741ef2ea351d82',
    messagingSenderId: '400663275175',
    projectId: 'dhikrs-2b082',
    storageBucket: 'dhikrs-2b082.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBFbBTPGnxnrsntHL4AM7IJ7hzcgRzK58',
    appId: '1:400663275175:ios:19e877033ea5169a351d82',
    messagingSenderId: '400663275175',
    projectId: 'dhikrs-2b082',
    storageBucket: 'dhikrs-2b082.firebasestorage.app',
    iosBundleId: 'com.example.dhikrs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBFbBTPGnxnrsntHL4AM7IJ7hzcgRzK58',
    appId: '1:400663275175:ios:19e877033ea5169a351d82',
    messagingSenderId: '400663275175',
    projectId: 'dhikrs-2b082',
    storageBucket: 'dhikrs-2b082.firebasestorage.app',
    iosBundleId: 'com.example.dhikrs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLmuc8UQYqT1YX07B8F4bkhRMbn5p-ek4',
    appId: '1:400663275175:web:713ad3880fd34783351d82',
    messagingSenderId: '400663275175',
    projectId: 'dhikrs-2b082',
    authDomain: 'dhikrs-2b082.firebaseapp.com',
    storageBucket: 'dhikrs-2b082.firebasestorage.app',
    measurementId: 'G-9MJBDRNQ2S',
  );
}
