name: Flutter Windows Desktop CI/CD with Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            %LOCALAPPDATA%\Pub\Cache
            %USERPROFILE%\.flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Flutter pub get
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build Windows application
        run: flutter build windows --release

      - name: Upload Windows application artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-app
          path: build/windows/runner/Release/

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token secret created earlier
          tag: v1.0.0  # Adjust this as needed
          name: "Release v1.0.0"
          body: "This is an automated release of the Flutter Windows application."
          draft: false
          prerelease: false
          files: build/windows/runner/Release/*.exe
