name: Flutter Windows Desktop CI/CD with Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter SDK
        run: |
          # Clone Flutter SDK from GitHub (make sure to check out the correct branch)
          git clone https://github.com/flutter/flutter.git --branch stable --depth 1
          # Add flutter/bin directory to the PATH
          echo "$(pwd)/flutter/bin" >> $GITHUB_PATH
          # Verify flutter installation by running flutter doctor
          flutter doctor

      - name: Install dependencies
        run: flutter pub get

      - name: Run Windows tests
        run: flutter test --platform windows

      - name: Build Windows application
        run: flutter build windows

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/windows/runner/Release/dhikr.exe