name: Flutter Windows Desktop CI/CD with Release

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: windows-latest  # Using a Windows runner for building the Windows application

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # Use the stable version of Flutter

      - name: Install dependencies
        run: flutter pub get

      - name: Run Windows tests
        run: flutter test --platform windows  # Run the tests for the Windows platform

      - name: Build Windows application
        run: flutter build windows  # Build the Windows application

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/windows/runner/Release/dhikr.exe  # Path to your built Windows application